name: tm-medals

services:
  api:
    build:
      context: api
    image: danonthemoon/tm-medals-api:latest
    restart: unless-stopped
    environment:
      DATABASE_CONNSTR: postgres://tmmedals:Passw0rd!@db:5432/tmmedals?pool_max_conns=10
      ADMIN_KEY: developer-test-key
      HOST: 0.0.0.0
    ports:
      - 8081:8081
    networks:
      - server-network
    depends_on:
      - db
  ingress:
    image: nginx
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - ./ingresssim/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - server-network
    depends_on:
      - api
  db:
    image: postgres:16
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: Passw0rd!
      POSTGRES_USER: tmmedals
    networks:
      - server-network
    ports:
      - 5432:5432

networks:
  server-network:
    driver: bridge
