name: tm-medals

services:
  api:
    build:
      context: api
    image: danonthemoon/tm-medals-api:latest
    restart: unless-stopped
    environment:
      DATABASE_CONNSTR: postgres://tmmedals:Passw0rd!@db:5432/tmmedals?pool_max_conns=10
      ADMIN_KEY: developer-test-key
      TM_URL: http://tmsim:8100
    ports:
      - 8081:8081
    networks:
      - server-network
  # app:
  #   build:
  #     context: app
  #   image: danonthemoon/tm-medals-app:latest
  #   restart: unless-stopped
  #   ports:
  #     - 8080:80
  #   networks:
  #     - server-network
  ingress:
    image: nginx
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - ./ingresssim/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - server-network
  db:
    image: postgres:16
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: Passw0rd!
      POSTGRES_USER: tmmedals
    networks:
      - server-network
    ports:
      - 5432:5432
  tmsim:
    image: mockoon/cli:8.1.1
    command: ["-d", "/data/mockoon.json", "-p", "8100"]
    restart: unless-stopped
    networks:
      - server-network
    ports:
      - 8100:8100
    volumes:
      - ./tmsim/:/data:ro

networks:
  server-network:
    driver: bridge
