version: "0.5"

processes:
  api:
    working_dir: api
    command: bun run watch
    # readiness_probe:
    #   http_get:
    #     host: localhost
    #     scheme: http
    #     path: "/ready"
    #     port: 8081
    environment:
      - "DATABASE_CONNSTR=postgres://tmmedals:Passw0rd!@localhost:5432/tmmedals?pool_max_conns=10"
      - "ADMIN_KEY=developer-test-key"
      - "HOST=localhost"
      - "DEBUG=true"
  db:
    working_dir: .
    command: docker compose up db
    shutdown:
      command: docker compose stop db
  plugin:
    working_dir: plugin
    command: bash .bin/build.sh -w
